### ISSUE TITLE
Bug: patch method broken (request method name & typing) 

### ISSUE THREAD

**Issue by Wouterkoorn** [surrealdb/surrealdb.py#99]
### Describe the bug

The `Surreal.patch` method is currently broken due to the wrong method name being used in the request.
It is also wrongly typed, the expected input should be a list of dict, not a sole dict. And the return type should allow a single dict.

### Steps to reproduce

Currently:
```py
await db.update("table:id", {"field": "value"})
```
`surrealdb.ws.SurrealPermissionException: Method not found`

---

After changing the Request method in `Surreal.patch` from "modify" to "patch":
```py
await db.update("table:id", {"field": "value"})
```
`surrealdb.ws.SurrealPermissionException: There was a problem with the database: The JSON Patch contains invalid operations. Operations must be an array`

---

Now using an array as documented here: https://surrealdb.com/docs/surrealdb/integration/websocket#patch
```py
await db.patch("table:id", [
    {"op": "replace", "path": "/field", "value": "value2"}
])
```
Success! But typing of both the data param, and the return type, is still wrong.

### Expected behaviour

1. The request method name should be changed from "modify" to "patch", similar to https://github.com/surrealdb/surrealdb.py/pull/85
2. The `data` parameter should by typed to expect an Array, e.g. `List[Dict[str, Any]]`
3. The return type allows a single dict, same as https://github.com/surrealdb/surrealdb.py/issues/97

### SurrealDB version

Not relevant

### surrealdb.py version

0.3.2 (latest as of 2024-04-02)

### Contact Details

Ideally in the issue itself. Otherwise: 6qmf6te8@duck.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by agarfer1** [comment]
Hello,

I wanted to add that I am experiencing the same error with the merge method.

My surrealDB version is also v1.3.1 but from docker, and the SDK 0.3.2 as well.

The same merge functionality directly called via Surrealist works as expected.

This is how I am calling the method:

```
await db.merge(my_record_id, { 'test' : 'test' })
```


The complete Traceback:

```
Traceback (most recent call last):
  File "/home/user/tests/parser.py", line 150, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/tests/parser.py", line 53, in main
    await db.merge(my_record_id, { 'test' : 'test' })
  File "/home/user/.local/lib/python3.10/site-packages/surrealdb/ws.py", line 536, in merge
    success: ResponseSuccess = _validate_response(
  File "/home/user/.local/lib/python3.10/site-packages/surrealdb/ws.py", line 161, in _validate_response
    raise exception(response.message)
surrealdb.ws.SurrealPermissionException: Method not found
```


Please let me know if it should be better to open a new issue for this and I will do it.
